var context = require('azure-function-context-mock');
import { employeeObjectTransformation } from "../share-code/update-employee";
import { TransformedEmployee } from "../type/type";

describe("test update employee logic",() => {
  beforeAll(async () => {
  });

  afterAll(() => {
  })

  it("test employee object transformation", () => {
    const data: any =  {
      "WS.PERSON_ID": "90001498",
      "WS.PERSONNEL_NUMBER": "90001498",
      "WS.MAIN_POSITION": "Y",
      "WS.SCG_EMPLOYEE_ID": "0140-012831",
      "WS.NAME_PREFIX_THAI": "นาย",
      "WS.FIRST_NAME_THAI": "วินัย",
      "WS.LAST_NAME_THAI": "กล่อมจิตต์",
      "WS.TITLE_ENGLISH": "Mr.",
      "WS.FIRST_NAME_ENGLISH": "Winai",
      "WS.LAST_NAME_ENGLISH": "Klomchit",
      "WS.NICK_NAME": "นัย",
      "WS.ACTION": null,
      "WS.ACTION_DATE": null,
      "WS.POSITION_ID": "00059733",
      "WS.POSITION_ENTRY_DATE": "01.12.2018",
      "WS.POSITION_NAME_ENGLISH": "Maintenance Overhaul and Consultancy Supervisor-Electrical",
      "WS.POSITION_NAME_THAI": "Maintenance Overhaul and Consultancy Supervisor-Electrical",
      "WS.ORGANIZATION_UNIT_ID": "00013896",
      "WS.EMPLOYEE_ORGANIZATION_NAME_ENG": "Electrical",
      "WS.EMPLOYEE_ORGANIZATION_NAME_THA": "Electrical",
      "WS.SUB1_BUSINESS_UNIT_ENGLISH": "Cement and Construction Solution Business",
      "WS.SUB1_BUSINESS_UNIT_THAI": "Cement and Construction Solution Business",
      "WS.SUB11_BUSINESS_UNIT_ENGLISH": "Engineering Industrial Services&Smart Utilities",
      "WS.SUB11_BUSINESS_UNIT_THAI": "Engineering Industrial Services&Smart Utilities",
      "WS.SUB1COMPANY_ENGLISH": null,
      "WS.SUB1COMPANY_THAI": null,
      "WS.DIVISION_ENGLISH": "Maintenance Repair Overhaul",
      "WS.DIVISION_THAI": "Maintenance Repair Overhaul",
      "WS.SUB1DIVISION_ENGLISH": null,
      "WS.SUB1DIVISION_THAI": null,
      "WS.DEPARTMENT_ENGLISH": "Maintenance Repair Overhaul - Northeast",
      "WS.DEPARTMENT_THAI": "Maintenance Repair Overhaul - Northeast",
      "WS.SUB1DEPARTMENT_ENGLISH": "Maintenance Overhaul and Consultancy",
      "WS.SUB1DEPARTMENT_THAI": "Maintenance Overhaul and Consultancy",
      "WS.SECTION_ENGLISH": "Electrical",
      "WS.SECTION_THAI": "Electrical",
      "WS.SUB1SECTION_ENGLISH": null,
      "WS.SUB1SECTION_THAI": null,
      "WS.SHIFT_ENGLISH": null,
      "WS.SHIFT_THAI": null,
      "WS.SUB1SHIFT_ENGLISH": null,
      "WS.SUB1SHIFT_THAI": null,
      "WS.COST_CENTER": "0141-02A20",
      "WS.ORGANIZATION_UNIT_ID_OF_PARENT": "00013894",
      "WS.PERSONNEL_AREA_CODE": "T010",
      "WS.PERSONNEL_AREA": "SKK - Kaeng Khoi",
      "WS.COMPANY_CODE": "0140",
      "WS.COMPANY_ENGLISH": "The Siam Cement (Kaeng Khoi) Co., Ltd.",
      "WS.COMPANY_THAI": "บริษัท ปูนซิเมนต์ไทย (แก่งคอย) จำกัด",
      "WS.BUSINESS_UNIT_CODE": "CBM",
      "WS.BUSINESS_UNIT_DESCRIPTION_ENGL": "SCG Cement-Building Materials",
      "WS.BUSINESS_UNIT_DESCRIPTION_THAI": "เอสซีจี ซิเมนต์-ผลิตภัณฑ์ก่อสร้าง",
      "WS.HEAD_OF_ORGANIZATION_UNIT": "N",
      "WS.SCG_PL_CODE": "S2",
      "WS.SCG_PL_DESCRIPTION": null,
      "WS.PL_EMPLOYEE_SUBGROUP_OBJECTS": "S2",
      "WS.PL_DATE": null,
      "WS.EMPLOYEE_GROUP_CODE": "B",
      "WS.EMPLOYEE_GROUP_TEXT": "Permanent Employee",
      "WS.EMPLOYMENT_STATUS_CODE": "3",
      "WS.EMPLOYMENT_STATUS_TEXT": "Active",
      "WS.EMPLOYEE_TYPE_ID": null,
      "WS.SERVICE_DATE": "01.12.1986",
      "WS.SERVICE_YEARS": "34",
      "WS.SERVICE_MONTHS": "11",
      "WS.TERMINATION_DATE": null,
      "WS.TERMINATION_REASON": null,
      "WS.MANAGER_PERSONNEL_NUMBER": "90001522",
      "WS.MANAGER_NAME": "Mr. Monchai Vongsri",
      "WS.MANAGER_POSITION": "00059731",
      "WS.MANAGER_POSITION_NAME": "Maintenance Overhaul and Consultancy M.",
      "WS.MANAGER_SCG_EMP_ID": "0140-013484",
      "WS.MANAGER_EMAIL": "MONCHAVO@SCG.COM",
      "WS.MANAGER_USER_ID": "MONCHAVO",
      "WS.HIGHEST_EDUCATION_LEVEL": null,
      "WS.EDUCATION": null,
      "WS.GENDER": null,
      "WS.NATIONALITY_CODE": null,
      "WS.BLOOD_TYPE": null,
      "WS.BIRTHDATE": "23.03.1966",
      "WS.MARITAL_STATUS": null,
      "WS.IDENTIFICATION_CARD_ID": null,
      "WS.TAX_ID": null,
      "WS.SPOUSE_FIRST_NAME": null,
      "WS.SPOUSE_LAST_NAME": null,
      "WS.EMERGENCY_CONTACT_NAME_PRIMARY": null,
      "WS.EMERGENCY_CONTACT_TELEPHONE_NU": null,
      "WS.EMERGENCY_CONTACT_MOBILE_NUMBE": null,
      "WS.ADDRESS_NUMBER": null,
      "WS.VILLAGESOI": null,
      "WS.STREET_ROAD": null,
      "WS.SUB_DISTRICTTAMBOL": null,
      "WS.DISTRICT": null,
      "WS.PROVINCE": null,
      "WS.POSTAL_CODE": null,
      "WS.OFFICE_ADDRESS__BUILDING": null,
      "WS.OFFICE_ADDRESS__FLOOR": null,
      "WS.OFFICE_ADDRESS__ROOM": null,
      "WS.OFFICE_ADDRESS__PROVINCE": null,
      "WS.EMAIL_ADDRESS_BUSINESS": "WINKLO@SCG.COM",
      "WS.TELEPHONE_BUSINESS": null,
      "WS.TELEPHONE_BESIDE": null,
      "WS.EMAIL_HOME": null,
      "WS.EMAIL_OTHER": null,
      "WS.TELEPHONE_HOME": null,
      "WS.TELEPHONE_MOBILE": null,
      "WS.USER_ID": "WINKLO",
      "WS.ACCOUNT_LOCKED": "0",
      "WS.LAST_SIGN_ON_DATETIME": "17.11.2021 23:31:07",
      "WS.LAST_UPDATE_DATETIME": "09.08.2021",
      "WS.VENDORCUSTOMER_ID": "0050042202",
      "WS.FLAG_IINSERT_DDELETE_UUPDATE": "U",
      "WS.SYSTEM_DATE_TIME": "25.11.2021",
      "WS.BANK_ID_PRIMARY": null,
      "WS.BRANCH_ID_PRIMARY": null,
      "WS.BANK_NAME_PRIMARY": null,
      "WS.BRANCH_NAME_PRIMARY": null,
      "WS.ACCOUNT_ID": null,
      "WS.OLD_COMPANY": null,
      "WS.OLD_SCG_EMP_ID": null,
      "WS.MIDDLE_NAME": null,
      "WS.PERSONNEL_SUB_AREA_CODE": "TH66",
      "WS.PERSONNEL_SUB_AREA": "Saraburi",
      "WS.WORKING_LOCATION_CODE": "014T01",
      "WS.WORKING_LOCATION": "SKK - Kaeng Khoi",
      "WS.AGE_YEARS": "55",
      "WS.AGE_MONTHS": "8",
      "WS.EDU_LEVEL_ENTRY_DEGREE": "Vocational",
      "WS.FIELD_OF_EDU_ENTRY_DEGREE": "Electric/Electronic/Tele/Instru/Control",
      "WS.CERTIFICATE_ENTRY_DEGREE": "Vocational Certificate",
      "WS.FACULTY_ENTRY_DEGREE": "ช่างอิเล็กทรอนิกส์",
      "WS.MAJOR_ENTRY_DEGREE": "ช่างอิเล็กทรอนิกส์",
      "WS.INSTITUTE_ENTRY_DEGREE": "Surin Technical College",
      "WS.HEALTH_CHECKUP_DATE": "09.07.2020"
    }

    const now = new Date()
    const mockResult: TransformedEmployee = {
      person_id: '90001498',
      personnel_number: '90001498',
      scg_employee_id: '0140-012831',
      name_prefix_th: 'นาย',
      first_name_th: 'วินัย',
      last_name_th: 'กล่อมจิตต์',
      nickname: 'นัย',
      position_name_th: 'Maintenance Overhaul and Consultancy Supervisor-Electrical',
      company: 'บริษัท ปูนซิเมนต์ไทย (แก่งคอย) จำกัด',
      business_unit: 'Cement and Construction Solution Business',
      division: 'Maintenance Repair Overhaul',
      department: 'Maintenance Repair Overhaul - Northeast',
      employment_status: 'Active',
      contract_type: 'Permanent Employee',
      username: 'WINKLO@SCG.COM',
      email: 'WINKLO@SCG.COM',
      pl: 'S2',
      scg_pl: 'S2',
      sub1_shift_th: null,
      shift_th: null,
      sub1_section_th: null,
      section_th: 'Electrical',
      sub1_department_th: 'Maintenance Overhaul and Consultancy',
      sub1_division_th: null,
      sub1_company_th: null,
      sub1_1_business_unit_th: 'Engineering Industrial Services&Smart Utilities',
      business_unit_desc_th: 'เอสซีจี ซิเมนต์-ผลิตภัณฑ์ก่อสร้าง',
      updated_at: now
    }
    
    const transformData: TransformedEmployee = employeeObjectTransformation(data)
    transformData.updated_at = now
    expect(transformData).toEqual(mockResult)
  });

});
